services:
  - type: web
    name: curd_app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn curd_project.wsgi:application
